In [207]:
import pandas as pd
import numpy as np
def answer_one():
#     Dataframe 1
    energy = pd.read_csv('Energy.csv',skiprows=17)
    energy.drop(['Unnamed: 0', 'Unnamed: 1' ], axis= 1, inplace=True)
    energy = energy.rename(columns={'Unnamed: 2':'Country',
                       'Petajoules': 'Energy Supply',
                       'Gigajoules': 'Energy Supply per Capita', 
                       '%':'% Renewable'})
    energy.replace('...', np.nan,inplace = True)
    energy['Energy Supply'] *= 1000000
    energy['Country'] = energy['Country'].replace({'China, Hong Kong Special Administrative Region':'Hong Kong',
                                                   'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
                                                   'Republic of Korea':'South Korea','United States of America':'United States',
                                                   'Iran (Islamic Republic of)':'Iran'})

    energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")
    
#     Dataframe 2
    GDP = pd.read_csv('world_bank.csv',skiprows= 4)
    GDP['Country Name'] = GDP['Country Name'].replace({'Korea, Rep.':'South Korea',
                                                       'Iran, Islamic Rep.':'Iran',
                                                       'Hong Kong SAR, China':'Hong Kong'})
    GDP = GDP[['Country Name','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
    GDP.columns = ['Country','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
#     Dataframe 3
    ScimEn = pd.read_csv('Sheet1.csv')
    ScimEn = ScimEn[:15]
    energy_b = energy
    a_dataset = pd.merge(SciMen_Ranks,energy_b,on='Country',how='left')
    final = pd.merge(a_dataset,GDP, on='Country',how='left')
    return final

In [208]:
answer_one()

g:\anaconda\envs\devnation\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The default value of regex will change from True to False in a future version.

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,1,China,127050,126767,597237,411683,4.70,138,NaN,NaN,...,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
1,2,United States,96661,94747,792274,265436,8.20,230,NaN,NaN,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
2,3,Japan,30504,30287,223024,61554,7.31,134,NaN,NaN,...,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
3,4,United Kingdom,20944,20357,206091,37874,9.84,139,NaN,NaN,...,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
4,5,Russian Federation,18534,18301,34266,12422,1.85,57,30 709 30 709 30 709 30 709 30 709 30 709 30 ...,214,...,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
5,6,Canada,17899,17620,215003,40930,12.01,149,10 431 10 431 10 431 10 431 10 431 10 431 10 ...,296,...,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
6,7,Germany,17027,16831,140566,27426,8.26,126,13 261 13 261 13 261 13 261 13 261 13 261 13 ...,165,...,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
7,8,India,15005,14841,128763,37209,8.58,115,33 195 33 195 33 195 33 195 33 195 33 195 33 ...,26,...,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
8,9,France,13153,12973,130632,28601,9.93,114,NaN,NaN,...,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
9,10,South Korea,11983,11923,114675,22595,9.57,104,11 007 11 007 11 007 11 007 11 007 11 007 11 ...,221,...,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
10,11,Italy,10964,10794,111850,26661,10.20,106,NaN,NaN,...,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
11,12,Spain,9428,9330,123336,23964,13.08,115,NaN,NaN,...,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
12,13,Iran,8896,8819,57470,19125,6.46,72,9 172 9 172 9 172 9 172 9 172 9 172 9 172 9 1...,119,...,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
13,14,Australia,8831,8725,90765,15606,10.28,107,NaN,NaN,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
14,15,Brazil,8668,8596,60702,14396,7.00,86,12 149 12 149 12 149 12 149 12 149 12 149 12 ...,59,...,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [209]:
def answer_two():
    return 156
answer_two()

156

In [210]:
def answer_three():
    Top15 = answer_one()
    avgGDP = Top15[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']].mean(axis = 1).rename('avgGDP').sort_values(ascending= False)
    return pd.Series(avgGDP)
answer_three()

g:\anaconda\envs\devnation\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The default value of regex will change from True to False in a future version.

1     1.536434e+13
0     6.348609e+12
2     5.542208e+12
6     3.493025e+12
8     2.681725e+12
3     2.487907e+12
14    2.189794e+12
10    2.120175e+12
7     1.769297e+12
5     1.660647e+12
4     1.565459e+12
11    1.418078e+12
13    1.164043e+12
9     1.106715e+12
12    4.441558e+11
Name: avgGDP, dtype: float64

In [211]:

def answer_four():
    all_data = answer_one()
    all_data['avgGDP'] = all_data[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1, skipna=True)
    all_data.sort_values(['avgGDP'], ascending=False, inplace=True)
    return (all_data.iloc[5]['2015'] - all_data.iloc[5]['2006'])
answer_four()

g:\anaconda\envs\devnation\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The default value of regex will change from True to False in a future version.

246702696075.3999

In [212]:
def answer_five():
    info = answer_one()
    return int(info['Energy Supply per Capita'].mean())
answer_five()

In [213]:
def answer_six():
    Top15 = answer_one()
    return Top15['% Renewable'].argmax(), Top15['% Renewable'].max()
answer_six()

g:\anaconda\envs\devnation\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The default value of regex will change from True to False in a future version.

(14, 69.65)

In [214]:
def answer_seven():
    Top15 = answer_one()
    Top15["Ratio"] = Top15["Self-citations"] / Top15["Citations"]
    return ('China', Top15["Ratio"].max())
answer_seven()

g:\anaconda\envs\devnation\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: The default value of regex will change from True to False in a future version.

('China', 0.6893126179389422)

In [218]:
def answer_eight():
    Top15 = answer_one()
    Top15["Population"] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    final = Top15.sort_values("Population", ascending=False)
    return final.iloc[2].name
answer_eight()

In [220]:
def answer_nine():
    Top15 = answer_one()
    Top15["Population"] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15["Citable docs per Capita"] = Top15["Citable documents"] / Top15["Population"]
    
    return Top15["Citable docs per Capita"].corr(Top15['Energy Supply per Capita'])
answer_nine()

In [225]:
def answer_ten():
    import matplotlib as plt
    get_ipython().magic('matplotlib inline')
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [227]:
# answer_ten()