### Q1
Create a function add_numbers which takes 4 parameters
1. x (integer)
2. y (integer)
3. z (integer)
4. flag (Boolean)
z and flag are optional parameters
if function receives z then function should return the sum of x y and z else
return the sum of x and y
if flag is True also print the statement
“Flag is True”

In [1]:
# z and flag are optional
# if-statement will return if function receives z otherwise else-statement will return
# “Flag is True” will be only printed if boolean-flag is True

def add_numbers(x, y, z=None, flag=None):
    if flag:
        print("Flag is True")
    if z:
        return (x + y + z)
    else:
        return (x + y)

In [2]:
print(f"1 --> Sum only X and Y = {add_numbers(4,7)} \n")
print(f"2 --> Sum X, Y and Z = {add_numbers(4,7,11)} \n")
print(f"3 --> Sum X, Y, Z and Flag = {add_numbers(4,7,11,True)} \n")
print(f"4 --> Sum X, Y, Z and Flag = {add_numbers(4,7,11,False)} \n")

# You have to specify the parameter name too in case you want to pass only desired positional arguements
print(f"5 --> Sum X, Y, Z and Flag = {add_numbers(4,7,flag=True)} \n")

# Here if we won't specify that it is boolean flag parameter that is TRUE, then it will consider it the
# third positional arguement and consider TRUE as 1 for z-parameter
print(f"6 --> Sum X, Y and Z = {add_numbers(4,7,True)}")

1 --> Sum only X and Y = 11

2 --> Sum X, Y and Z = 22

Flag is True
3 --> Sum X, Y, Z and Flag = 22

4 --> Sum X, Y, Z and Flag = 22

Flag is True
5 --> Sum X, Y, Z and Flag = 11

6 --> Sum X, Y and Z = 12

### Q2
Write a function get_datetime(int) that takes a param number_of_days and
if the number is divisible by 2 returns (current_datetime + number_of_days) and
if number is divisible by 3 returns (current_datetime - number_of_days)
else return current_datetime

In [3]:
# Importing required Libraries
import datetime as dt
import time as tm

# Function to get Get Date and Time according to the condition
def get_datetime(num_of_days):
#     Check and return if num_of_days are divisible by 2
    if (num_of_days % 2) == 0:
        return dt.datetime.today() + dt.timedelta(days=num_of_days)
    
#     Check and return if num_of_days are divisible by 3
    elif (num_of_days % 3) == 0:
        return dt.datetime.today() - dt.timedelta(days=num_of_days)
    
#     Returning the current Date and Time
    else:
        return dt.datetime.today()

In [4]:
print(f"When Days are Devisible by 2 : {get_datetime(4)}")
print(f"When Days are Devisible by 3 : {get_datetime(9)}")
print(f"When Days are not Devisible by 2 OR 3 : {get_datetime(7)}")

When Days are Devisible by 2 : 2021-08-11 12:21:08.283276
When Days are Devisible by 3 : 2021-07-29 12:21:08.283276
When Days are not Devisible by 2 OR 3 : 2021-08-07 12:21:08.284273

### Q3
Write a function concat_lst that takes two list as a parameter and combine two list together into single list
and should not contains duplicate values.
You must use loop to solve this question

In [5]:
# This function will simply append the elements from 2nd List to the 1st List one by one
def concat_lst(list_1, list_2):
#   Appending List 2 to List 1
    final_list = []
    for element in list_2:
        list_1.append(element)
        
    for element in list_1:
        if element not in final_list:
            final_list.append(element)

#   Removing duplicates and returning the resultant list
    return final_list

In [6]:
l1 = [1,2,3,4,5,6,7]
l2 = [5,6,7,8,9,10,11]

result_list = concat_lst(l1,l2)
result_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### Q4
Write a function string_case using map that takes list of characters and return
List of tuples with containing lower and upper case of that character’s list
Final Output must contain unique tuple element

In [7]:
# This function will take List of chars
def string_case(char_list):
#   Getting Lower and Upper Cases
#   Removing Duplicates
#   Returning the List
    return list(set(map(convert_low_up, char_list)))

# Function to convert each element to Lower and Upper Case
def convert_low_up(x):
    return x.lower(), x.upper()

In [8]:
my_list = ['a', 'r', 'h','a', 'm']
resultant_list = string_case(my_list)
resultant_list

[('h', 'H'), ('m', 'M'), ('a', 'A'), ('r', 'R')]

### Q5
Write a function get_city_mpg_avg, that groups the cars by number of cylinders, and
finding the average cty mpg for each group.
Output should be in the list of tuples
Output = [ (5,20),(4,18),(3,16) ]
Note:
1. Use MPG.csv file
2. First index of tuple shows the number of cylinders and second index shows the average
3. Result should be sorted by first tuple index by using lambda functions

In [28]:
import csv

# Function to get unique cylinders
def all_distinct_cylinders(csv_all_data):
    all_cylinders_list = []
    
# Reading the whole data but appending only number of cylinders to list
    for ele in csv_all_data:
        if ele['cyl'] not in all_cylinders_list:
            all_cylinders_list.append(ele['cyl'])
    
# Prinitng first 10 number of cylinders from the list
    print(f"List of All Number of Cylinders -------> {all_cylinders_list[:15]}")

# Returning the list of unique number of cylinders
    return all_cylinders_list

# Function to get Milage
def get_city_mpg_avg():
    
#   Reading CSV file
    with open('mpg.csv') as mpg_csv:
        csv_all_data = list(csv.DictReader(mpg_csv))
    
    all_dist_cylinders = all_distinct_cylinders(csv_all_data)
    
    resultant_list = []
    for cyl in all_dist_cylinders:
        milage_sum = 0
        car_counter = 0
        
        print(f"Current Distinct Number of Cylinders -------> {cyl}")
        
        for main_data_row in csv_all_data:
            if main_data_row['cyl'] == cyl:
                milage_sum += float(main_data_row['cty'])
                car_counter += 1
        
        print(f"Milage Sum for {cyl} Number of Cylinders -------> {milage_sum}")
        
        resultant_list.append((cyl, milage_sum / car_counter))
        resultant_list.sort(key=lambda x:x[0])

    return resultant_list

In [29]:
print("--------Calculating City Milage Average----------")
print(f"-------Average Milage according to Number of Cylinders-----\n {get_city_mpg_avg()}")

--------Calculating City Milage Average----------
List of All Number of Cylinders -------> ['4', '6', '8', '5']
Current Distinct Number of Cylinders -------> 4
Milage Sum for 4 Number of Cylinders -------> 1702.0
Current Distinct Number of Cylinders -------> 6
Milage Sum for 6 Number of Cylinders -------> 1281.0
Current Distinct Number of Cylinders -------> 8
Milage Sum for 8 Number of Cylinders -------> 880.0
Current Distinct Number of Cylinders -------> 5
Milage Sum for 5 Number of Cylinders -------> 82.0
-------Average Milage according to Number of Cylinders-----
 [('4', 21.012345679012345), ('5', 20.5), ('6', 16.21518987341772), ('8', 12.571428571428571)]

### Q6
Write a function get_hwy_mpg_avg find the average hwy mpg for each class of vehicle
Hwy mpg means highway mileage
1. Use MPG.csv file
2. Hwy mpg is found as hwy column in a file
3. Vehicle class is found as class column in a file
4. Sort Hwy Mpg in ascending order
Output sample: [('pickup', 16.88),('suv', 18.13),('minivan', 22.36),('2seater', 24.80),('midsize', 27.29),
('subcompact', 28.14), ('compact', 28.30)]

In [11]:
import csv

# Function to get unique cylinders
def all_distinct_vehicle_classes(csv_all_data):
    all_classes_list = []
    
# Reading the whole data but appending only class of vehicle to list
    for ele in csv_all_data:
        if ele not in all_classes_list:
            all_classes_list.append(ele['class'])
    
# Prinitng some of classes from the list
    print(f"List of All Distinct Classes -------> {all_classes_list[:7]}")

# Returning the list of unique classes
    return all_classes_list

# Function to get Milage
def get_hwy_mpg_avg():
    
#   Reading CSV file
    with open('mpg.csv') as mpg_csv:
        csv_all_data = list(csv.DictReader(mpg_csv))
    
    all_dist_classes = all_distinct_vehicle_classes(csv_all_data)
    
    resultant_list = []
    for vehicle_class in all_dist_classes:
        milage_sum = 0
        car_counter = 0
        
        print(f"Current Distinct Class -------> {vehicle_class}")
        
        for main_data_row in csv_all_data:
            if main_data_row['class'] == vehicle_class:
                milage_sum += float(main_data_row['hwy'])
                car_counter += 1
        
        print(f"Milage Sum for {vehicle_class} Class -------> {milage_sum}")
        
        resultant_list.append((vehicle_class, milage_sum / car_counter))
        resultant_list.sort(key=lambda x:x[1])

    return resultant_list

In [12]:
print("--------Calculating Highway Milage Average according to Vehicle Class----------")
get_hwy_mpg_avg()

--------Calculating Highway Milage Average according to Vehicle Class----------
List of All Distinct Classes -------> ['compact', 'compact', 'compact', 'compact', 'compact', 'compact', 'compact']
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> 2seater
Milage Sum for 2seater Class -------> 124.0
Current Distinct Class -------> 2seater
Milage Sum for 2seater Class -------> 124.0
Current Distinct Class -------> 2seater
Milage Sum for 2seater Class -------> 124.0
Current Distinct Class -------> 2seater
Milage Sum for 2seater Class -------> 124.0
Current Distinct Class -------> 2seater
Milage Sum for 2seater Class -------> 124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> minivan
Milage Sum for minivan Class -------> 246.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> suv
Milage Sum for suv Class -------> 1124.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> pickup
Milage Sum for pickup Class -------> 557.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> compact
Milage Sum for compact Class -------> 1330.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> subcompact
Milage Sum for subcompact Class -------> 985.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0
Current Distinct Class -------> midsize
Milage Sum for midsize Class -------> 1119.0

[('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('pickup', 16.87878787878788),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('suv', 18.129032258064516),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('minivan', 22.363636363636363),
 ('2seater', 24.8),
 ('2seater', 24.8),
 ('2seater', 24.8),
 ('2seater', 24.8),
 ('2seater', 24.8),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('midsize', 27.29268292682927),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('subcompact', 28.142857142857142),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553),
 ('compact', 28.29787234042553)]

### Q7
Create a class Student with the following getters and setters
1. Constructor
a. Create an Object with following parameters
i. Name
ii. Batch No
iii. Address
iv. Age
v. Father Name
vi. City

2. New
a. Students with age more than 18 are not allowed in the school
b. Students of Lahore Islamabad Faisalabad Karachi are allowed
3. Setters
a. Name (str)
b. Batch no (int)
c. Address (str)
d. Age (str)
e. Father name (str)
f. City (str)
4. Getters
a. Name
b. Batch no
c. Address
d. Age
e. Father name
f. City
5. Create a new class called DevnationStudents which is a child class of Student
a. Write a constructor that
i. That calls the Parent Class Constructor
ii. Also save courses and marks as empty list in the child constructor
b. Write setter functions
i. Add courses
1. Takes a list of courses
2. Add only those courses in the list which are not already in the
ii. Add courses_marks
1. This takes the list of dictionaries
2. If the particular exists in the courses lists then the particular dictionary
should be added in the marks list
3. Marks list should not contains duplicate entries of same courses

c. Write getter functions
i. Get courses
ii. Get Marks

In [13]:
# Student class with its attributes
class Student:

#  Creating Object
    def __new__(cls, name, batch_no, address, age, father_name, city):
        cities = ["Lahore", "Islamabad", "Faisalabad", "Karachi"]
        if (age < 19) and (city in cities):
            print("YOU ARE ALLOWED")
            inst = object.__new__(cls)
            return inst
        else:
            print("You are NOT ALLOWED. Make sure you are under 19. Or try changing your City")
#  You can also use: if (age < 19) and (city == "Lahore" or city == "Islamabad" or city == "Faisalabad" or city == "Karachi")

        
#  Class Constructor - Initializing Object attributes
    def __init__(self, name, batch_no, address, age, father_name, city):
        self.name = name
        self.batch_no = batch_no
        self.address = address 
        self.age = age
        self.father_name = father_name
        self.city = city
        
    
#  Setters - To set desired values to attributes
    def set_name(self,name):
        self.name = name
        
    def set_batch_no(self,batch_no):
        self.batch_no = batch_no
        
    def set_address(self,address):
        self.address = address
        
    def set_age(self,age):
        self.age = age
        
    def set_father_name(self,father_name):
        self.father_name = father_name
        
    def set_city(self,city):
        self.city = city
        
        
#  Getters - To get values of attributes
    def get_name(self):
        return self.name
        
    def get_batch_no(self):
        return self.batch_no
        
    def get_address(self):
        return self.address
    
    def get_age(self):
        return self.age
        
    def get_father_name(self):
        return self.father_name
        
    def get_city(self):
        return self.city
        

# Creating Child class of the Student class (Inheritance)
class DevnationStudents(Student):
    
#  Class Constructor - Passing attribute values to the Student Class 
    def __init__(self, name, batch_no, address, age, father_name, city, courses=[], marks=[]):
        super().__init__(name, batch_no, address, age, father_name, city)
        self.courses = courses
        self.courses_marks_list = marks
        
#  Setters
#  Method to add course if it is not already in the list
    def set_add_course(self, courses_list):
        for course in courses_list:
            if course not in self.courses:
                self.courses.append(course)

# Check if a course is already marked
    def check_dup(self, value):
        flag = False
        for existing_dict in self.courses_marks_list:
            if existing_dict["course"] == value:
                flag = True
        return flag
# Adding new course and it's marks (dictionary) to the main course_marks_list
    def set_courses_marks(self, course_marks_list):
        for new_dict in course_marks_list:
            if new_dict["course"] in self.courses:
                if (self.check_dup(new_dict["course"])):
                    continue
                else:
                    self.courses_marks_list.append(new_dict)
    
#  Getters
# Method to get list of courses
    def get_course(self):
        return self.courses

# Method to get list of courses and their marks
    def get_course_marks(self):
        return self.courses_marks_list
    
# Method to get latest personal info of the Student
    def get_latest_info(self):
        return f"{self.get_name()} Son of {self.get_father_name()}, and {self.get_age()} years old living in {self.get_address()}, {self.get_city()}, is a Student of DevNation in Batch {self.get_batch_no()}. His current courses are {self.get_course()} with the following marks {self.get_course_marks()}"

In [14]:
# Creating 1st Object
student_1 = DevnationStudents("Arham", 3, "My_Home", 18, "Ghulam Mustafa", "Lahore")

YOU ARE ALLOWED

In [15]:
student_1.set_add_course(["Stats", "Python", "Software Engineering"])
student_1.get_course()

['Stats', 'Python', 'Software Engineering']

In [16]:
student_1.set_courses_marks([{"course": "Python", "marks": "92"},{"course": "Maths", "marks": "82"}])
student_1.get_course_marks()

[{'course': 'Python', 'marks': '92'}]

In [17]:
student_1.set_courses_marks([{"course": "Stats", "marks": "92"},{"course": "Python", "marks": "82"}])
student_1.get_course_marks()

[{'course': 'Python', 'marks': '92'}, {'course': 'Stats', 'marks': '92'}]

In [18]:
student_1.set_name("Arham Mustafa")
student_1.get_name()

'Arham Mustafa'

In [19]:
student_1.set_age(22)
student_1.get_age()

22

In [20]:
student_1.set_city("Sahiwal")
student_1.get_city()

'Sahiwal'

In [21]:
student_1.get_latest_info()

"Arham Mustafa Son of Ghulam Mustafa, and 22 years old living in My_Home, Sahiwal, is a Student of DevNation in Batch 3. His current courses are ['Stats', 'Python', 'Software Engineering'] with the following marks [{'course': 'Python', 'marks': '92'}, {'course': 'Stats', 'marks': '92'}]"

### Q8
Write a function get_indices that receives the list of integers nums and an integer target, return indices of
the two numbers such that they add up to target. You may assume that each input would have exactly one
solution, and you may not use the same element twice.

In [22]:
# Method to get indices of those numbers that added up to form the target number

def get_indices(int_list, target):
    
# Select each element from the list one by one
# Add each element to the first selected element and compare it with target
# If matched return indices of those elements
    for num_idx_1 in range(0, len(int_list)):
        for num_idx_2 in range(0, len(int_list)):
            if (int_list[num_idx_1] + int_list[num_idx_2]) == target:
                return num_idx_1, num_idx_2
            else:
                continue

In [23]:
int_list = [13,2,19,7,11,15]
target_num = 20

result = list(get_indices(int_list, target_num))
result

[0, 3]

### Q9
Write a function backward_number. That a receives a number and return the number in backwards
Input = 1234
Output = 4321

In [24]:
# This method will return the reverse of a number using string slicing

def backward_number_list_slicing(num):

# First convert the number to String
# Reverse the string using string slicing
# Convert it again into int and return

    return int(str(num)[::-1])


# This same method can also be written as using mathematical logic

def backward_number(num):
    
# Initialize a Number with Zero, so that we will add our remainder in it
    reversed_number = 0
# Keep breaking the number into digits till number is greater than Zero
    while(num > 0):
        remainder = num % 10
        print(f"Remainder : {remainder}")
        reversed_number = (reversed_number * 10) + remainder
        print(f"Reversed Number so far : {reversed_number}")
        num = num // 10
        print(f"Original Number after this break-up : {num}")
        
    return reversed_number

In [25]:
number = 14601000
print(f"Result using List Slicing = {backward_number_list_slicing(number)}\n")

result = backward_number(number)
print(f"Reversed Number Result: {result}")

Result using List Slicing = 10641

Remainder : 0
Reversed Number so far : 0
Original Number after this break-up : 1460100
Remainder : 0
Reversed Number so far : 0
Original Number after this break-up : 146010
Remainder : 0
Reversed Number so far : 0
Original Number after this break-up : 14601
Remainder : 1
Reversed Number so far : 1
Original Number after this break-up : 1460
Remainder : 0
Reversed Number so far : 10
Original Number after this break-up : 146
Remainder : 6
Reversed Number so far : 106
Original Number after this break-up : 14
Remainder : 4
Reversed Number so far : 1064
Original Number after this break-up : 1
Remainder : 1
Reversed Number so far : 10641
Original Number after this break-up : 0
Reversed Number Result: 10641

### Q10
Create a function remove_duplication that takes a list and remove duplication from list.
You cannot use set function

In [26]:
# This method will remove all the dupllications of the elements

def remove_duplication(dup_list):

# Create an empty list
# Traverse all the elements in the list
# Append element if is not already present in the newly created list
    new_list = []
    for ele in dup_list:
        if ele not in new_list:
                new_list.append(ele)
    return new_list

In [27]:
my_list = [1,2,3,8,6,3,2,7,1,3,7,8,4,3,1,3,2,7]

result = remove_duplication(my_list)
result

[1, 2, 3, 8, 6, 7, 4]